### PR TITLE
remove profile picture and insert project's github link

### PR DESCRIPTION
**Pull request by Priyanko9**
Screenshot 2023-04-08 at 12 33 26 AM

### CODE REVIEW

**Comment by ttebify** [comment]
Hi @Priyanko9 , thank you for your interest to contribute.

I see what you did there, awesome job. But I was looking at a solution that would replace the name and social link since this project is going to be open source I do not want to include a single individual as the developer.

So if it's possible,  could you change the Contact Developer to something else and the screen should show a way for the user to link to GitHub.

What do you think?

**Comment by ttebify** [comment]
An update on this matter - we need to wait for Mudit to see what they come up with since he has already taken ownership of the task. Thank you for your eagerness. You are always welcome to select another open issue or create one if you encounter any issues while utilizing the extension.

Looking forward to see what you can come up with, I will leave this open while we await update from Mudit

**Comment by Priyanko9** [comment]
Removed the name and social links

Screenshot 2023-04-08 at 3 14 24 PM

**Comment by ttebify** [comment]
Thank you. I'll merge this now. Can you remove the developer image file and any other assets that is no longer needed from the assets folder?

**Comment by Priyanko9** [comment]
Removed the developer image and github image

**Review by ttebify — APPROVED** [review]

**Comment by ttebify** [comment]
Amazing work @Priyanko9

**Pull request merged**
